version: '3'
services:
  next-app:
    image : jaeyun1650/marrymo_fe
    container_name: next-app
    expose:
      - 3000
    env_file:
     - /home/ubuntu/next/.env.local

    networks:
      - marrymo_net

networks:
  marrymo_net:
    external: true
