# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # kakao login settings
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # aws application-aws.yml
  profiles:
    active: ${AWS}

  # h2 database
  h2:
    console:
      enabled: true

  # mail settings
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${USER_GMAIL}
    password: ${MAILAPP_PW}
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    auth-code-expiration-millis: 300000

  # spring data jpa settings
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

  # redis settings
  data:
    redis:
      port: ${SPRING_REDIS_PORT}
      host: ${SPRING_REDIS_HOST}
      password: ${SPRING_REDIS_PASSWORD}

# log settings
logging:
  level:
    root: info
    site.marrymo.restapi: debug

# encoding utf-8
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  forward-headers-strategy: framework   # 추가

kakaopay:
  client_id: ${KAKAOPAY_CLIENT_ID}
  secret_key: ${KAKAOPAY_SECRET_KEY}
  redirect_url: ${KAKAOPAY_REDIRECT_URL}

#open-banking
open-banking:
  client_id: ${OPENBANK_CLIENT_ID}
  client_secret: ${OPENBANK_CLIENT_SECRET}

#mobank
mo-bank:
  client_id: ${MOBANK_CLIENT_ID}
  client_secret: ${MOBANK_CLIENT_SECRET}
  client_name: ${MOBANK_CLIENT_NAME}
  client_account: ${MOBANK_CLIENT_ACCOUNT}

#jwt
jwt:
  salt: ${JWT_SALT}
  access-token:
    expiretime: ${JWT_ACCESS_TOKEN_EXPIRETIME}
  refresh-token:
    expiretime: ${JWT_REFRESH_TOKEN_EXPIRETIME}

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
  api-docs:
    path: /v3/api-docs
